exp_name: dw

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

seed: 0

data:
  dataset_file: datasets/dw/dw_full_14k.h5

model:
  hidden_dims: [100, 100, 100]
  activation: tanh
  norm: layernorm

train:
  lr: 0.0005
  epochs: 5000
  bnre_lambda: 10.0
  batch_size: 128
  print_every: 10
  clip_max_norm: 5.00
  save_every: 500
  checkpoint_dirname: "checkpoints"
  stop_after_epochs: 250
