exp_name: sinusoid_transformer

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

seed: 0
device: cpu

data:
  dataset_file: datasets/sinusoid/sinusoid_noisy_with_masks.h5

model:
  d_model: 16
  num_layers: 2
  num_heads: 2
  transformer_mlp_dim: 128
  transformer_activation: gelu

  head_hidden_dims: [50, 50, 50]
  head_activation: tanh
  head_norm: layernorm

train:
  lr: 0.0005
  epochs: 500
  bnre_lambda: 1000.0
  batch_size: 128
  print_every: 1
  clip_max_norm: 5.0
  save_every: 50
  checkpoint_dirname: "checkpoints"
  stop_after_epochs: 50