exp_name: amber501_flux_skewers_transformer

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

seed: 0
device: cpu

data:
  dataset_file: /Users/diegogonzalez/Documents/Research/ENIGMA/BNRE-HMC/jax_bnre_hmc/datasets/amber501/tau_skewers_z5.00_with_masks_miniset.hdf5

model:
  d_model: 16
  num_layers: 1
  num_heads: 2
  transformer_mlp_dim: 128
  transformer_activation: gelu

  head_hidden_dims: [128, 128, 128]
  head_activation: tanh
  head_norm: layernorm

train:
  lr: 0.00005
  epochs: 1000
  bnre_lambda: 100.0
  batch_size: 256
  print_every: 1
  clip_max_norm: 5.00 # null for no clipping
  save_every: 50 # save latest checkpoint every N epochs (0 or null to disable)
  checkpoint_dirname: "checkpoints"
  stop_after_epochs: 100 # early stopping patience (null to disable)
