exp_name: amber501_p1d

hydra:
  job:
    chdir: false
  run:
    dir: outputs/${exp_name}/${now:%Y-%m-%d}_${now:%H-%M-%S}

seed: 0

data:
  dataset_file: /Users/diegogonzalez/Documents/Research/ENIGMA/BNRE-HMC/jax_bnre_hmc/datasets/amber501/mocks_z5.00_snr30.0.hdf5
  validation_fraction: 0.2
  test_fraction: 0.2
  n_train: 500000
  n_val: 50000
  n_test: 50000

model:
  hidden_dims: [50, 50, 50]
  activation: tanh
  norm: layernorm

train:
  lr: 0.0005
  epochs: 1000
  bnre_gamma: 1000.0
  batch_size: 128
  print_every: 10
  clip_max_norm: 5.00 # null for no clipping
  save_every: 100 # save latest checkpoint every N epochs (0 or null to disable)
  checkpoint_dirname: "checkpoints"
  stop_after_epochs: 50 # early stopping patience (null to disable)

